# Generated by Django 4.2 on 2023-04-16 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bmw', '0002_audi'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Audi',
        ),
    ]
