# Generated by Django 4.2 on 2023-04-16 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bmw', '0003_delete_audi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Mashina nomi', max_length=255, verbose_name='Nomi')),
                ('model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='bmw.bmw', verbose_name='madel')),
            ],
            options={
                'verbose_name': 'Audi',
                'verbose_name_plural': 'Audi',
            },
        ),
    ]
