# Generated by Django 4.2 on 2023-04-16 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bmw', '0004_audi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bmw',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bmw.bmw', verbose_name='madel'),
        ),
    ]
