# Generated by Django 4.2 on 2023-04-16 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bmw', '0005_alter_bmw_model'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Audi',
            new_name='Captiva',
        ),
    ]
