# Generated by Django 4.2 on 2023-04-16 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bmw', '0006_rename_audi_captiva'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='captiva',
            options={'verbose_name': 'Captiva', 'verbose_name_plural': 'Captiva'},
        ),
    ]
