# Generated by Django 4.2 on 2023-04-16 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Mashina nomi', max_length=255, verbose_name='Nomi')),
                ('date', models.DateTimeField()),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audi.audi', verbose_name='madel')),
            ],
            options={
                'verbose_name': 'Audi',
                'verbose_name_plural': 'Audi',
            },
        ),
    ]
