# Generated by Django 4.2 on 2023-04-16 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('audi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audi',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='audi.audi', verbose_name='madel'),
        ),
    ]
