# Generated by Django 4.2 on 2023-04-16 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audi', '0002_alter_audi_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audi',
            name='model',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='madel'),
        ),
    ]
